### ISSUE TITLE
[SPO] harden error handling for single-document issues

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#1582]
### Problem Description
SPO connector will fail if a single request errors. 

<img width="629" alt="Screenshot 2023-09-05 at 12 26 09 PM" src="https://github.com/elastic/connectors-python/assets/5288246/a352c162-18ab-434e-bf14-bb6587765de2">

We should:
- [ ] make sure that this specific error does not occur
- [ ] make the whole connector more flexible and resilient to these types of errors

**Comment by seanstory** [comment]
Example of another error we should be able to retry or move past:

```
Received 400 response from https://graph.microsoft.com/v1.0/sites/retailstarbucks1com.sharepoint.com,8cf7065d-af86-4ece-9df3-9c7faf57f801,c388935f-df6f-4be6-9792-05175814bcfb/lists/1d7882ce-8766-44f1-81ef-8f5c8e8d9639/items?$select=createdDateTime,id,lastModifiedDateTime,weburl,createdBy,lastModifiedBy,contentType&$expand=fields($select=Title,Link,Attachments,LinkTitle,LinkFilename,Description,Conversation)
```

<details><summary>full stack trace</summary>

```
[FMWK][12:44:01][WARNING] [Sync Job id: DjoWlIoB26kkwmCbnNr-, connector id: DToVlIoB26kkwmCb0dpW, index name: search-retail] Received 400 response from https://graph.microsoft.com/v1.0/sites/retailstarbucks1com.sharepoint.com,8cf7065d-af86-4ece-9df3-9c7faf57f801,c388935f-df6f-4be6-9792-05175814bcfb/lists/1d7882ce-8766-44f1-81ef-8f5c8e8d9639/items?$select=createdDateTime,id,lastModifiedDateTime,weburl,createdBy,lastModifiedBy,contentType&$expand=fields($select=Title,Link,Attachments,LinkTitle,LinkFilename,Description,Conversation)
[FMWK][12:44:01][CRITICAL] [Sync Job id: DjoWlIoB26kkwmCbnNr-, connector id: DToVlIoB26kkwmCb0dpW, index name: search-retail] The document fetcher failed
Traceback (most recent call last):
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sources/sharepoint_online.py", line 402, in _get
    async with self._http_session.get(
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/lib/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://graph.microsoft.com/v1.0/sites/retailstarbucks1com.sharepoint.com,8cf7065d-af86-4ece-9df3-9c7faf57f801,c388935f-df6f-4be6-9792-05175814bcfb/lists/1d7882ce-8766-44f1-81ef-8f5c8e8d9639/items?$select=createdDateTime,id,lastModifiedDateTime,weburl,createdBy,lastModifiedBy,contentType&$expand=fields($select=Title,Link,Attachments,LinkTitle,LinkFilename,Description,Conversation)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/es/sink.py", line 387, in get_docs
    async for count, doc in aenumerate(generator):
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/utils.py", line 689, in aenumerate
    async for elem in asequence:
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/logger.py", line 134, in __anext__
    return await self.gen.__anext__()
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/es/sink.py", line 360, in _decorate_with_metrics_span
    async for doc in generator:
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sync_job_runner.py", line 310, in prepare_docs
    async for doc, lazy_download, operation in self.generator():
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sync_job_runner.py", line 342, in generator
    async for doc, lazy_download in self.data_provider.get_docs(
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sources/sharepoint_online.py", line 1547, in get_docs
    async for list_item, download_func in self.site_list_items(
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sources/sharepoint_online.py", line 1777, in site_list_items
    async for list_item in self.client.site_list_items(site_id, site_list_id):
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sources/sharepoint_online.py", line 745, in site_list_items
    async for page in self._graph_api_client.scroll(
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sources/sharepoint_online.py", line 347, in scroll
    graph_data = await self._get_json(scroll_url)
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sources/sharepoint_online.py", line 371, in _get_json
    async with self._get(absolute_url) as resp:
  File "/Users/gustavollermalylarrain/miniforge3/envs/connector/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sources/sharepoint_online.py", line 295, in wrapped
    async for item in func(*args, **kwargs):
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sources/sharepoint_online.py", line 413, in _get
    await self._handle_client_response_error(absolute_url, e)
  File "/Users/gustavollermalylarrain/Documents/proyectos/elastic/starbucks/connectors-python/connectors/sources/sharepoint_online.py", line 443, in _handle_client_response_error
    raise BadRequestError from e
connectors.sources.sharepoint_online.BadRequestError
```

</details>

Why should we not consider this a real 400? Because it's really not. SPO lies.

<img width="1121" alt="Screenshot 2023-09-14 at 4 56 43 PM" src="https://github.com/elastic/connectors-python/assets/5288246/993e070f-66f5-4e1a-84ce-4f4308676554">

**Comment by seanstory** [comment]
another single-document failure issue: https://github.com/elastic/enterprise-search-team/issues/7044

**Comment by artem-shelkovnikov** [comment]
Haven't had those for a bit
