### ISSUE TITLE
Mongo SSL Configuration

### ISSUE THREAD

**Issue by amanpreet-s-maersk** [elastic/connectors#1973]
## Bug Description
Before PR #1937 , connector would connect to host `mongodb://<creds>@<url>:<port>/?ssl=true` without any errors.
This change adds `'tls': False` to the client_params which throws below error.
```shell
[FMWK][10:49:27][CRITICAL] Can not specify conflicting values for URI options ssl and tls.
Traceback (most recent call last):
  File "/Users/connectors/connectors/services/job_scheduling.py", line 150, in _run
    await self._schedule(connector)
  File "/Users/connectors/services/job_scheduling.py", line 92, in _schedule
    data_source = source_klass(connector.configuration)
  File "/Users/connectors/sources/mongo.py", line 129, in __init__
    self.client = AsyncIOMotorClient(host, **client_params)
  File "/Users/connectors/lib/python3.10/site-packages/motor/core.py", line 159, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
  File "/Users/connectors/lib/python3.10/site-packages/pymongo/mongo_client.py", line 714, in __init__
    opts = _handle_security_options(opts)
  File "/Users/connectors/lib/python3.10/site-packages/pymongo/uri_parser.py", line 220, in _handle_security_options
    raise InvalidURI(err_msg % (options.cased_key("ssl"), options.cased_key("tls")))
pymongo.errors.InvalidURI: Can not specify conflicting values for URI options ssl and tls.
``` 
ES - 8.11.1
Kibana - 8.11.1
Mongo: Azure Cosmos MongoDB
Server Version: 4.2

**Comment by seanstory** [comment]
Thanks for filing, @amanpreet-s-maersk . This looks like something we could catch in config validation, to make sure the host string and the SSL configs are aligned.

Just making sure, if you change the new config away from its default value and set `'tls': True`, it works, correct?

**Comment by seanstory** [comment]
@amanpreet-s-maersk just a note - we don't support using connector versions on a different version than the stack. If you're using ES/Kibana 8.11.x, you should be using connectors 8.11.x too. We'll still address this issue, but just want to keep you from running into others. 8.12.x and 8.13.x aren't even released yet.

**Comment by artem-shelkovnikov** [comment]
@amanpreet-s-maersk what if you remove `ssl=true` in the connection string and enable it via the configurable field `SSL/TLS connection`? Will it make it work?

**Comment by amanpreet-s-maersk** [comment]
@artem-shelkovnikov removing the `ssl=true` and using the `SSL/TLS` configuration field is working too.

**Comment by artem-shelkovnikov** [comment]
Sounds good, just wanted to make sure you're not blocked while we're resolving the issue :)

**Comment by parthpuri-elastic** [comment]
@seanstory, We have added validation regarding conflicting values of SSL. Do we need to do anything else? Otherwise, we can close this issue.

**Comment by seanstory** [comment]
Yep, I believe this issue was fixed by https://github.com/elastic/connectors/pull/2018.

Closing
