### ISSUE TITLE
Error log on forced job cancelation

### ISSUE THREAD

**Issue by seanstory** [elastic/connectors#1985]
## Bug Description
Found as part of https://github.com/elastic/enterprise-search-team/issues/6378

When testing job cancelation, one time I observed this in the logs:

<details><summary>Logs with error and stacktrace</summary>

```
[FMWK][20:08:18][ERROR] [Connector id: IjiRX4wB-Jf4HtfTHr_U, index name: search-dls-1, Sync job id: OjihX4wB-Jf4HtfTe797] Sync job did not stop within 5 seconds of canceling. Force-canceling.
[FMWK][20:08:18][DEBUG] [Connector id: IjiRX4wB-Jf4HtfTHr_U, index name: search-dls-1, Sync job id: OjihX4wB-Jf4HtfTe797] Job reporting task is stopped.
[FMWK][20:08:18][INFO] [Connector id: IjiRX4wB-Jf4HtfTHr_U, index name: search-dls-1, Sync job id: OjihX4wB-Jf4HtfTe797] Sync ended with status canceled -- created: 487 | updated: 0 | deleted: 0 (took 225 seconds)
[FMWK][20:08:18][DEBUG] Sleep canceled
[FMWK][20:08:18][DEBUG] [Connector id: IjiRX4wB-Jf4HtfTHr_U, index name: search-dls-1, Sync job id: OjihX4wB-Jf4HtfTe797] Posting to Sharepoint Endpoint: https://graph.microsoft.com/v1.0/$batch.
[FMWK][20:08:18][DEBUG] [Connector id: IjiRX4wB-Jf4HtfTHr_U, index name: search-dls-1, Sync job id: OjihX4wB-Jf4HtfTe797] Posting to Sharepoint Endpoint: https://graph.microsoft.com/v1.0/$batch.
[FMWK][20:08:18][DEBUG] [Connector id: IjiRX4wB-Jf4HtfTHr_U, index name: search-dls-1, Sync job id: OjihX4wB-Jf4HtfTe797] Posting to Sharepoint Endpoint: https://graph.microsoft.com/v1.0/$batch.
[FMWK][20:08:18][DEBUG] [get_doc call] 487-_decorate_with_metrics_span took 13.126895189285278 seconds.
[FMWK][20:08:18][CRITICAL] [Connector id: IjiRX4wB-Jf4HtfTHr_U, index name: search-dls-1, Sync job id: OjihX4wB-Jf4HtfTe797] Document extractor failed
Traceback (most recent call last):
  File "/app/connectors/es/sink.py", line 362, in run
    await self.get_docs(generator)
  File "/app/connectors/es/sink.py", line 410, in get_docs
    async for count, doc in aenumerate(generator):
  File "/app/connectors/utils.py", line 800, in aenumerate
    async for elem in asequence:
  File "/app/connectors/logger.py", line 176, in __anext__
    return await self.gen.__anext__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/connectors/es/sink.py", line 384, in _decorate_with_metrics_span
    async for doc in generator:
  File "/app/connectors/sync_job_runner.py", line 309, in prepare_docs
    async for doc, lazy_download, operation in self.generator():
  File "/app/connectors/sync_job_runner.py", line 341, in generator
    async for doc, lazy_download in self.data_provider.get_docs(
  File "/app/connectors/sources/sharepoint_online.py", line 1623, in get_docs
    async for drive_item in self._drive_items_batch_with_permissions(
  File "/app/connectors/sources/sharepoint_online.py", line 1577, in _drive_items_batch_with_permissions
    async for permissions_response in self.client.drive_items_permissions_batch(
  File "/app/connectors/sources/sharepoint_online.py", line 810, in drive_items_permissions_batch
    batch_response = await self._graph_api_client.post(batch_url, batch_request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/connectors/sources/sharepoint_online.py", line 363, in post
    async with self._post(url, payload) as resp:
  File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/connectors/sources/sharepoint_online.py", line 323, in wrapped
    async for item in func(*args, **kwargs, retry_count=retry):
  File "/app/connectors/sources/sharepoint_online.py", line 410, in _post
    async with self._http_session.post(
  File "/app/lib/python3.11/site-packages/aiohttp/client.py", line 1167, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/aiohttp/client.py", line 426, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
```

</details>

At the time, the connector in question (Sharepoint Online) was being throttled, and so my working theory is that we hit this edge case when our connector is sleeping for too long between retries and doesn't respond to the 5-second grace period to shut down gracefully. 

In particular, I'm concerned that the lines like:
```
[FMWK][20:08:18][ERROR] [Connector id: IjiRX4wB-Jf4HtfTHr_U, index name: search-dls-1, Sync job id: OjihX4wB-Jf4HtfTe797] Sync job did not stop within 5 seconds of canceling. Force-canceling.
...
[FMWK][20:08:18][CRITICAL] [Connector id: IjiRX4wB-Jf4HtfTHr_U, index name: search-dls-1, Sync job id: OjihX4wB-Jf4HtfTe797] Document extractor failed
Traceback (most recent call last):
```

are too alarming, and should be at WARN or maybe even at INFO/DEBUG. The resulting behavior was what I wanted after all - the job was canceled, and the sync job ended up in the correct (`canceled`) state.

### To Reproduce
Unclear, but maybe:

1. create an SPO connector
2. kick off a long-running sync that's likely to be throttled
3. when you see evidence of throttling happening, quickly cancel the sync
4. hopefully observe these errors

## Expected behavior
The job should be canceled and the logs should not indicate there were any "errors" - even if the cancelation was "forced."

## Environment
v8.12.0-BC.1

## Additional context
Slack thread: https://elastic.slack.com/archives/C01795T48LQ/p1702411870826699

**Comment by wangch079** [comment]
I agree that `ERROR` can be changed to `warning`.

The stack trace concerns me, which is thrown at line 377, but is expected to be caught at line 372:
https://github.com/elastic/connectors/blob/63b8486cdaeb38ddb3f5fff0f5350fe0280b7f47/connectors/es/sink.py#L372-L379

**Comment by wangch079** [comment]
I followed the steps and tried to reproduce it, I did see the `ERROR` log but not the stack trace.

<details><summary>Logs with noises removed</summary>

```
[FMWK][14:58:35][ERROR] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Sync job did not stop within 5 seconds of canceling. Force-canceling.
[FMWK][14:58:35][DEBUG] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Job reporting task is stopped.
[FMWK][14:58:35][ERROR] Exception found for task Task-8508: 
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8501: 
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8504: 
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8509: 
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8503: 
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8505: 
NoneType: None
[FMWK][14:58:35][INFO] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Sync ended with status canceled -- created: 1417 | updated: 0 | deleted: 0 (took 802 seconds)
[FMWK][14:58:35][WARNING] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Graph API dropped the connection. It might indicate, that connector makes too many requests - decrease concurrency settings, otherwise Graph API can block this app.
[FMWK][14:58:35][ERROR] Exception found for task Task-8502: Session is closed
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8558: Session is closed
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8559: Session is closed
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8560: Session is closed
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8561: Session is closed
NoneType: None
[FMWK][14:58:35][WARNING] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Graph API dropped the connection. It might indicate, that connector makes too many requests - decrease concurrency settings, otherwise Graph API can block this app.
[FMWK][14:58:35][ERROR] Exception found for task Task-8512: Session is closed
NoneType: None
[FMWK][14:58:35][WARNING] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Graph API dropped the connection. It might indicate, that connector makes too many requests - decrease concurrency settings, otherwise Graph API can block this app.
[FMWK][14:58:35][ERROR] Exception found for task Task-8513: Session is closed
NoneType: None
[FMWK][14:58:35][WARNING] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Graph API dropped the connection. It might indicate, that connector makes too many requests - decrease concurrency settings, otherwise Graph API can block this app.
[FMWK][14:58:35][WARNING] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Graph API dropped the connection. It might indicate, that connector makes too many requests - decrease concurrency settings, otherwise Graph API can block this app.
[FMWK][14:58:35][WARNING] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Graph API dropped the connection. It might indicate, that connector makes too many requests - decrease concurrency settings, otherwise Graph API can block this app.
[FMWK][14:58:35][WARNING] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Graph API dropped the connection. It might indicate, that connector makes too many requests - decrease concurrency settings, otherwise Graph API can block this app.
[FMWK][14:58:35][WARNING] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Graph API dropped the connection. It might indicate, that connector makes too many requests - decrease concurrency settings, otherwise Graph API can block this app.
[FMWK][14:58:35][WARNING] [Connector id: t5B-gIwBuY5vcbP2rMfO, index name: search-spo, Sync job id: D5DSgIwBuY5vcbP2OcjH] Graph API dropped the connection. It might indicate, that connector makes too many requests - decrease concurrency settings, otherwise Graph API can block this app.
[FMWK][14:58:35][ERROR] Exception found for task Task-8549: Session is closed
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8542: Session is closed
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8546: Session is closed
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8539: Session is closed
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8537: Session is closed
NoneType: None
[FMWK][14:58:35][ERROR] Exception found for task Task-8541: Session is closed
NoneType: None
```

</details>

I think it's completely random and depends on whether `ForceCanceledError` or any other error is thrown first.

https://github.com/elastic/connectors/blob/63b8486cdaeb38ddb3f5fff0f5350fe0280b7f47/connectors/es/sink.py#L372-L379

What I plan to do is to change the error-catching logic, so that if the `Extractor` or `Sink` is forcibly canceled, the error will be ignored.
