### ISSUE TITLE
[CLI] Index list fails against ES3 (managed)

### ISSUE THREAD

**Issue by vidok** [elastic/connectors#2499]
## Bug Description
Running ./bin/connectors index list against an ES3 project logged in with an API key (no restrictions) I get the following error:

```
./bin/connectors index list                                                                                                               
[FMWK][18:46:32][WARNING] Client method 'stats' retry 1: api error with status 410
Traceback (most recent call last):
  File "/Users/rodney/Code/elastic/connectors/./bin/connectors", line 33, in <module>
    sys.exit(load_entry_point('elasticsearch-connectors', 'console_scripts', 'connectors')())
  File "/Users/rodney/Code/elastic/connectors/connectors/connectors_cli.py", line 636, in main
    cli()
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/rodney/Code/elastic/connectors/connectors/connectors_cli.py", line 396, in list_indices
    indices = index.list_indices()
  File "/Users/rodney/Code/elastic/connectors/connectors/cli/index.py", line 20, in list_indices
    return asyncio.run(self.__list_indices())["indices"]
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/rodney/Code/elastic/connectors/connectors/cli/index.py", line 39, in __list_indices
    raise e
  File "/Users/rodney/Code/elastic/connectors/connectors/cli/index.py", line 37, in __list_indices
    return await self.cli_client.list_indices()
  File "/Users/rodney/Code/elastic/connectors/connectors/es/management_client.py", line 189, in list_indices
    return await self._retrier.execute_with_retry(
  File "/Users/rodney/Code/elastic/connectors/connectors/es/client.py", line 234, in execute_with_retry
    result = await func()
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/elasticsearch/_async/client/indices.py", line 4404, in stats
    return await self.perform_request(  # type: ignore[return-value]
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/elasticsearch/_async/client/_base.py", line 423, in perform_request
    return await self._client.perform_request(
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/elasticsearch/_async/client/_base.py", line 271, in perform_request
    response = await self._perform_request(
  File "/Users/rodney/Code/elastic/connectors/lib/python3.10/site-packages/elasticsearch/_async/client/_base.py", line 352, in _perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.ApiError: ApiError(410, 'api_not_available_exception', 'Request for uri [/_stats] with method [GET] exists but is not available when running in serverless mode')
```

### To Reproduce
1. Create a managed project. 
2. Generate an API key
3. Create an index (e.g. via DevTools)
4. Configure the CLI using `./connectors login --method apikey`
5. Run `./connectors index list`
6. See the error

## Expected behavior
The CLI displays the list of the indices. 

## Environment
8.14 BC2

**Comment by vidok** [comment]
Fixed by https://github.com/elastic/connectors/pull/2511
