### ISSUE TITLE
[Sharepoint Online] Connector fails when missing body in response

### ISSUE THREAD

**Issue by bean710** [elastic/connectors#2590]
## Bug Description
When doing a batch API request to the Graph API, sometimes it will respond with a 503 and no body. In this case, when pushing the error up, `None` is returned on the `body` property, because the field is present in the response (but probably null?), causing the proceeding `get`s to throw an error. 

https://github.com/elastic/connectors/blob/502f666814f147669ce703f6ad0ffb01ebf98e8f/connectors/sources/sharepoint_online.py#L439

### To Reproduce
I've made a python script to reproduce the behavior based on the response from the logs:
```
import json

test_string = """{"id": "1234", "status": 503, "headers": {"Link": "<https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=v1.0,Removal&from=2021-09-01&to=2021-10-01>;rel='deprecation';type='text/html',<https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=v1.0,Removal&from=2021-09-01&to=2021-10-01>;rel='deprecation';type='text/html'", "Deprecation": "Fri, 03 Sep 2021 23:59:59 GMT", "Sunset": "Sun, 01 Oct 2023 23:59:59 GMT"}, "body": null}"""

response = json.loads(test_string)

body = response.get("body", {})
print(type(body))
error = body.get("error", {})
message = error.get("message")
```

## Expected behavior
I would expect it to be able to resolve to `None` or throw another (more clear) error if a `None` body is not supported.
Maybe something like this:
```
message = response.get("body", {}).get("error", {}).get("message") if response.get("body") else None
```

## Environment

I'm running from source and only a few commits behind main.

## Additional context

The full stacktrace:

```
[FMWK][12:29:43][CRITICAL] [Connector id: JVur4Y4BM4YOrFqvPEzu, index name: search-sharepoint-debugging, Sync job id: jTM7v48BRdqpVZ6xai--] Document extractor failed
Traceback (most recent call last):
  File "/Users/benjaminkeener/connector-main/connectors/es/sink.py", line 487, in run
    await self.get_docs(generator)
  File "/Users/benjaminkeener/connector-main/connectors/es/sink.py", line 539, in get_docs
    async for count, doc in aenumerate(generator):
  File "/Users/benjaminkeener/connector-main/connectors/utils.py", line 823, in aenumerate
    async for elem in asequence:
  File "/Users/benjaminkeener/connector-main/connectors/logger.py", line 247, in __anext__
    return await self.gen.__anext__()
  File "/Users/benjaminkeener/connector-main/connectors/es/sink.py", line 521, in _decorate_with_metrics_span
    async for doc in generator:
  File "/Users/benjaminkeener/connector-main/connectors/sync_job_runner.py", line 450, in prepare_docs
    async for doc, lazy_download, operation in self.generator():
  File "/Users/benjaminkeener/connector-main/connectors/sync_job_runner.py", line 486, in generator
    async for doc, lazy_download in self.data_provider.get_docs(
  File "/Users/benjaminkeener/connector-main/connectors/sources/sharepoint_online.py", line 1627, in get_docs
    ):
  File "/Users/benjaminkeener/connector-main/connectors/sources/sharepoint_online.py", line 1581, in _drive_items_batch_with_permissions
  File "/Users/benjaminkeener/connector-main/connectors/sources/sharepoint_online.py", line 810, in drive_items_permissions_batch
    batch_request = {"requests": requests}
  File "/Users/benjaminkeener/connector-main/connectors/sources/sharepoint_online.py", line 363, in post
    async with self._post(url, payload) as resp:
  File "/usr/local/Cellar/python@3.10/3.10.13_2/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/benjaminkeener/connector-main/connectors/sources/sharepoint_online.py", line 323, in wrapped
    async for item in func(*args, **kwargs, retry_count=retry):
  File "/Users/benjaminkeener/connector-main/connectors/sources/sharepoint_online.py", line 414, in _post
    await self._check_batch_items_for_errors(absolute_url, resp)
  File "/Users/benjaminkeener/connector-main/connectors/sources/sharepoint_online.py", line 439, in _check_batch_items_for_errors
    message=response.get("body", {}).get("error", {}).get("message"),
AttributeError: 'NoneType' object has no attribute 'get'
```

Here's what the connector outputs to the logs as the response from the batch request:
```
 Batch request item failed with: {'id': '1234', 'status': 503, 'headers': {'Link': '<https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=v1.0,Removal&from=2021-09-01&to=2021-10-01>;rel="deprecation";type="text/html",<https://developer.microsoft-tst.com/en-us/graph/changes?$filterby=v1.0,Removal&from=2021-09-01&to=2021-10-01>;rel="deprecation";type="text/html"', 'Deprecation': 'Fri, 03 Sep 2021 23:59:59 GMT', 'Sunset': 'Sun, 01 Oct 2023 23:59:59 GMT'}, 'body': None}
```

**Comment by seanstory** [comment]
Thanks for the detailed report and investigation! Seems like a straightforward fix. 👍

**Comment by artem-shelkovnikov** [comment]
I think we have an util function that safely traverses the hash. We need to switch as many places as possible to fix it too.
