### ISSUE TITLE
Docker: elasticsearch.ca_certs is not recognized as a config option for the Connector Service 8.16.0

### ISSUE THREAD

**Issue by odennhen** [elastic/connectors#3004]
## Bug Description
When trying to provide a ca-bundle to the Connector Service version 8.16.0, the Connector Service refuses to recognize the setting as a valid configuration option. It therefore prints a traceback and quits.

### To Reproduce
1. Provide the Docker image with a mounted volume containing a configuration file with elasticsearch.ca_certs as a set option, and a matching ca bundle file.
2. Attempt to run /app/bin/elastic-ingest using the mounted configuration file as configuration.
3. The following is printed to the terminal:
```
[FMWK][15:34:48][INFO] Running connector service version 8.16.0
[FMWK][15:34:48][INFO] Loading config from /config/config.yml
[FMWK][15:34:48][INFO] Bye
Traceback (most recent call last):
  File "/app/bin/elastic-ingest", line 33, in <module>
    sys.exit(load_entry_point('elasticsearch-connectors', 'console_scripts', 'elastic-ingest')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/connectors/service_cli.py", line 233, in main
    return run(action, config_file, log_level, filebeat, service_type, uvloop)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/connectors/service_cli.py", line 172, in run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app/connectors/service_cli.py", line 44, in _start_service
    preflight = PreflightCheck(config, __version__)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/connectors/preflight_check.py", line 22, in __init__
    self.es_management_client = ESManagementClient(self.elastic_config)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/connectors/es/management_client.py", line 37, in __init__
    super().__init__(config)
  File "/app/connectors/es/client.py", line 111, in __init__
    self.client = AsyncElasticsearch(**options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/elasticsearch/_async/client/__init__.py", line 400, in __init__
    _transport = transport_class(
                 ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/elastic_transport/_async_transport.py", line 141, in __init__
    super().__init__(
  File "/app/.venv/lib/python3.11/site-packages/elastic_transport/_transport.py", line 237, in __init__
    self.node_pool: NodePool = node_pool_class(
                               ^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/elastic_transport/_node_pool.py", line 188, in __init__
    self._all_nodes[node_config] = self._node_class(node_config)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.11/site-packages/elastic_transport/_node/_http_aiohttp.py", line 107, in __init__
    raise ValueError("ca_certs parameter is not a path")
ValueError: ca_certs parameter is not a path
```
## Expected behavior
The Connector service starts up and connects to Elasticsearch using the provided configuration file and ca bundle.

## Environment
Docker Desktop on Windows 11, version 4.22.0 (117440)
Elasticsearch, Kibana, and Elastic Connectors all at version 8.16.0 and in the same Docker network.
PostgreSQL 17.2 also sharing the same Docker network

## Additional context
I could run the Connector Service without the elasticsearch.ca_certs setting, but it failed to connect to Elasticsearch due to the self-signed certificate in use.

**Comment by seanstory** [comment]
Hi @odennhen - thanks for filing! This is definitely unexpected behavior. We're looking into it on our side. In the mean time, have you tried downgrading to 8.15.x connectors?
Alternatively, if you make your image's openSSL trust your self-signed cert, that should be a workaround that doesn't require the `ca_certs` config

**Comment by odennhen** [comment]
@seanstory Your maintainer was correct, I hadn't set the correct absolute path to the ca bundle in the configuration. Once that was sorted, the client was able to start in the Docker container.

Hopefully this issue will help explain the common mistake to other users, if nothing else!
